before:
  hooks:
    - go mod download
    - go generate ./...
builds:
-
  main: ./cmd/todo-list-server/main.go
  env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: todo-list-server
  github:
    owner: worldofprasanna
    name: homebrew-tap
  url_template: "https://github.com/worldofprasanna/todo-list-server/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: worldofprasanna
    email: prasannacse2005@gmail.com
  folder: Formula
  homepage: "http://worldofprasanna.in"
  description: "Simple plain todo. Sample project to setup proper golang project"
  
